# Generated by Django 3.0.2 on 2020-01-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20200123_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='idade',
            field=models.IntegerField(),
        ),
    ]
